stages:
  - build
  - test
  - deploy

# Job de build
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

# Job de test
test-job1:
  stage: test
  script:
    - echo "Install Python and run file"
    - apt-get update && apt-get install -y python3 python3-pip python3-venv
    - python3 -m venv venv  # Crée un environnement virtuel
    - source venv/bin/activate  # Active l'environnement virtuel
    - python --version
    - pip install -r requirements.txt
    - python hello.py
    - python main.py
    - python test_main.py

# Job de déploiement
deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
